/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_window_Keyboard_Key */

#ifndef _Included_org_jsfml_window_Keyboard_Key
#define _Included_org_jsfml_window_Keyboard_Key
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
