/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_window_Joystick */

#ifndef _Included_org_jsfml_window_Joystick
#define _Included_org_jsfml_window_Joystick
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jsfml_window_Joystick
 * Method:    isConnected
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jsfml_window_Joystick_isConnected
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jsfml_window_Joystick
 * Method:    getButtonCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_jsfml_window_Joystick_getButtonCount
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jsfml_window_Joystick
 * Method:    hasAxis
 * Signature: (ILorg/jsfml/window/Joystick$Axis;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jsfml_window_Joystick_hasAxis
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_jsfml_window_Joystick
 * Method:    isButtonPressed
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jsfml_window_Joystick_isButtonPressed
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_jsfml_window_Joystick
 * Method:    getAxisPosition
 * Signature: (ILorg/jsfml/window/Joystick$Axis;)F
 */
JNIEXPORT jfloat JNICALL Java_org_jsfml_window_Joystick_getAxisPosition
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_jsfml_window_Joystick
 * Method:    update
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jsfml_window_Joystick_update
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
