/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_audio_SoundSource_Status */

#ifndef _Included_org_jsfml_audio_SoundSource_Status
#define _Included_org_jsfml_audio_SoundSource_Status
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
