/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_graphics_Shape */

#ifndef _Included_org_jsfml_graphics_Shape
#define _Included_org_jsfml_graphics_Shape
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: debug */
/* Inaccessible static: numManaged */
/* Inaccessible static: numWrapped */
/*
 * Class:     org_jsfml_graphics_Shape
 * Method:    nativeSetTexture
 * Signature: (Lorg/jsfml/graphics/Texture;Z)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_Shape_nativeSetTexture
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     org_jsfml_graphics_Shape
 * Method:    nativeSetTextureRect
 * Signature: (Lorg/jsfml/graphics/IntRect;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_Shape_nativeSetTextureRect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_jsfml_graphics_Shape
 * Method:    nativeSetFillColor
 * Signature: (Lorg/jsfml/graphics/Color;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_Shape_nativeSetFillColor
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_jsfml_graphics_Shape
 * Method:    nativeSetOutlineColor
 * Signature: (Lorg/jsfml/graphics/Color;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_Shape_nativeSetOutlineColor
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_jsfml_graphics_Shape
 * Method:    setOutlineThickness
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_Shape_setOutlineThickness
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     org_jsfml_graphics_Shape
 * Method:    getTextureRect
 * Signature: ()Lorg/jsfml/graphics/IntRect;
 */
JNIEXPORT jobject JNICALL Java_org_jsfml_graphics_Shape_getTextureRect
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_graphics_Shape
 * Method:    getFillColor
 * Signature: ()Lorg/jsfml/graphics/Color;
 */
JNIEXPORT jobject JNICALL Java_org_jsfml_graphics_Shape_getFillColor
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_graphics_Shape
 * Method:    getOutlineColor
 * Signature: ()Lorg/jsfml/graphics/Color;
 */
JNIEXPORT jobject JNICALL Java_org_jsfml_graphics_Shape_getOutlineColor
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_graphics_Shape
 * Method:    getOutlineThickness
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_jsfml_graphics_Shape_getOutlineThickness
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_graphics_Shape
 * Method:    getPointCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jsfml_graphics_Shape_getPointCount
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_graphics_Shape
 * Method:    nativeGetPoint
 * Signature: (I)Lorg/jsfml/system/Vector2f;
 */
JNIEXPORT jobject JNICALL Java_org_jsfml_graphics_Shape_nativeGetPoint
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_jsfml_graphics_Shape
 * Method:    getLocalBounds
 * Signature: ()Lorg/jsfml/graphics/FloatRect;
 */
JNIEXPORT jobject JNICALL Java_org_jsfml_graphics_Shape_getLocalBounds
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_graphics_Shape
 * Method:    getGlobalBounds
 * Signature: ()Lorg/jsfml/graphics/FloatRect;
 */
JNIEXPORT jobject JNICALL Java_org_jsfml_graphics_Shape_getGlobalBounds
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
