/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_graphics_Shape */

#ifndef _Included_org_jsfml_graphics_Shape
#define _Included_org_jsfml_graphics_Shape
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jsfml_graphics_Shape
 * Method:    nativeSetTexture
 * Signature: (Lorg/jsfml/graphics/Texture;Z)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_Shape_nativeSetTexture
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     org_jsfml_graphics_Shape
 * Method:    nativeSetTextureRect
 * Signature: (Ljava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_Shape_nativeSetTextureRect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_jsfml_graphics_Shape
 * Method:    nativeSetFillColor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_Shape_nativeSetFillColor
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_jsfml_graphics_Shape
 * Method:    nativeSetOutlineColor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_Shape_nativeSetOutlineColor
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_jsfml_graphics_Shape
 * Method:    nativeSetOutlineThickness
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_Shape_nativeSetOutlineThickness
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     org_jsfml_graphics_Shape
 * Method:    nativeGetPointCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jsfml_graphics_Shape_nativeGetPointCount
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_graphics_Shape
 * Method:    nativeGetPoints
 * Signature: (ILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_Shape_nativeGetPoints
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_jsfml_graphics_Shape
 * Method:    nativeGetPoint
 * Signature: (I)Lorg/jsfml/system/Vector2f;
 */
JNIEXPORT jobject JNICALL Java_org_jsfml_graphics_Shape_nativeGetPoint
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_jsfml_graphics_Shape
 * Method:    nativeGetLocalBounds
 * Signature: (Ljava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_Shape_nativeGetLocalBounds
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_jsfml_graphics_Shape
 * Method:    nativeGetGlobalBounds
 * Signature: (Ljava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_Shape_nativeGetGlobalBounds
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
