/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_window_Keyboard */

#ifndef _Included_org_jsfml_window_Keyboard
#define _Included_org_jsfml_window_Keyboard
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jsfml_window_Keyboard
 * Method:    nativeIsKeyPressed
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jsfml_window_Keyboard_nativeIsKeyPressed
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
