/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_SFMLNative */

#ifndef _Included_org_jsfml_SFMLNative
#define _Included_org_jsfml_SFMLNative
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: JSFML_USER_HOME */
#undef org_jsfml_SFMLNative_MD5_LENGTH
#define org_jsfml_SFMLNative_MD5_LENGTH 32L
/* Inaccessible static: loaded */
/*
 * Class:     org_jsfml_SFMLNative
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jsfml_SFMLNative_nativeInit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
