/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_graphics_View */

#ifndef _Included_org_jsfml_graphics_View
#define _Included_org_jsfml_graphics_View
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: debug */
/* Inaccessible static: numManaged */
/* Inaccessible static: numWrapped */
/*
 * Class:     org_jsfml_graphics_View
 * Method:    nativeCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jsfml_graphics_View_nativeCreate
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_graphics_View
 * Method:    setCenter
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_View_setCenter
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     org_jsfml_graphics_View
 * Method:    setSize
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_View_setSize
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     org_jsfml_graphics_View
 * Method:    setRotation
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_View_setRotation
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     org_jsfml_graphics_View
 * Method:    nativeSetViewport
 * Signature: (Lorg/jsfml/graphics/FloatRect;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_View_nativeSetViewport
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_jsfml_graphics_View
 * Method:    nativeReset
 * Signature: (Lorg/jsfml/graphics/FloatRect;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_View_nativeReset
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_jsfml_graphics_View
 * Method:    getCenter
 * Signature: ()Lorg/jsfml/system/Vector2f;
 */
JNIEXPORT jobject JNICALL Java_org_jsfml_graphics_View_getCenter
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_graphics_View
 * Method:    getSize
 * Signature: ()Lorg/jsfml/system/Vector2f;
 */
JNIEXPORT jobject JNICALL Java_org_jsfml_graphics_View_getSize
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_graphics_View
 * Method:    getRotation
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_jsfml_graphics_View_getRotation
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_graphics_View
 * Method:    getViewport
 * Signature: ()Lorg/jsfml/graphics/FloatRect;
 */
JNIEXPORT jobject JNICALL Java_org_jsfml_graphics_View_getViewport
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_graphics_View
 * Method:    rotate
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_View_rotate
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     org_jsfml_graphics_View
 * Method:    move
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_View_move
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     org_jsfml_graphics_View
 * Method:    zoom
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_View_zoom
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
