/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_window_VideoMode */

#ifndef _Included_org_jsfml_window_VideoMode
#define _Included_org_jsfml_window_VideoMode
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jsfml_window_VideoMode_serialVersionUID
#define org_jsfml_window_VideoMode_serialVersionUID 8608938390916786270i64
/*
 * Class:     org_jsfml_window_VideoMode
 * Method:    nativeGetDesktopMode
 * Signature: (Ljava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_window_VideoMode_nativeGetDesktopMode
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_jsfml_window_VideoMode
 * Method:    nativeGetFullscreenModeCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jsfml_window_VideoMode_nativeGetFullscreenModeCount
  (JNIEnv *, jclass);

/*
 * Class:     org_jsfml_window_VideoMode
 * Method:    nativeGetFullscreenModes
 * Signature: (Ljava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_window_VideoMode_nativeGetFullscreenModes
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
