/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_ExPtr */

#ifndef _Included_org_jsfml_ExPtr
#define _Included_org_jsfml_ExPtr
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jsfml_ExPtr_NUM
#define org_jsfml_ExPtr_NUM 3L
#undef org_jsfml_ExPtr_DRAWABLE
#define org_jsfml_ExPtr_DRAWABLE 0L
#undef org_jsfml_ExPtr_TRANSFORMABLE
#define org_jsfml_ExPtr_TRANSFORMABLE 1L
#undef org_jsfml_ExPtr_RENDER_TARGET
#define org_jsfml_ExPtr_RENDER_TARGET 2L
#ifdef __cplusplus
}
#endif
#endif
