/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_graphics_SFMLNativeTransformable */

#ifndef _Included_org_jsfml_graphics_SFMLNativeTransformable
#define _Included_org_jsfml_graphics_SFMLNativeTransformable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jsfml_graphics_SFMLNativeTransformable
 * Method:    nativeSetPosition
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_SFMLNativeTransformable_nativeSetPosition
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     org_jsfml_graphics_SFMLNativeTransformable
 * Method:    nativeSetRotation
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_SFMLNativeTransformable_nativeSetRotation
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     org_jsfml_graphics_SFMLNativeTransformable
 * Method:    nativeSetScale
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_SFMLNativeTransformable_nativeSetScale
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     org_jsfml_graphics_SFMLNativeTransformable
 * Method:    nativeSetOrigin
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_SFMLNativeTransformable_nativeSetOrigin
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     org_jsfml_graphics_SFMLNativeTransformable
 * Method:    nativeGetTransform
 * Signature: (Ljava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_SFMLNativeTransformable_nativeGetTransform
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
