/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_graphics_Shader */

#ifndef _Included_org_jsfml_graphics_Shader
#define _Included_org_jsfml_graphics_Shader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jsfml_graphics_Shader
 * Method:    bind
 * Signature: (Lorg/jsfml/graphics/ConstShader;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_Shader_bind
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_jsfml_graphics_Shader
 * Method:    isAvailable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_jsfml_graphics_Shader_isAvailable
  (JNIEnv *, jclass);

/*
 * Class:     org_jsfml_graphics_Shader
 * Method:    nativeCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jsfml_graphics_Shader_nativeCreate
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_graphics_Shader
 * Method:    nativeDelete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_Shader_nativeDelete
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_graphics_Shader
 * Method:    nativeLoadFromSource1
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jsfml_graphics_Shader_nativeLoadFromSource1
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     org_jsfml_graphics_Shader
 * Method:    nativeLoadFromSource2
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jsfml_graphics_Shader_nativeLoadFromSource2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_jsfml_graphics_Shader
 * Method:    nativeSetParameterFloat
 * Signature: (Ljava/lang/String;F)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_Shader_nativeSetParameterFloat
  (JNIEnv *, jobject, jstring, jfloat);

/*
 * Class:     org_jsfml_graphics_Shader
 * Method:    nativeSetParameterVec2
 * Signature: (Ljava/lang/String;FF)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_Shader_nativeSetParameterVec2
  (JNIEnv *, jobject, jstring, jfloat, jfloat);

/*
 * Class:     org_jsfml_graphics_Shader
 * Method:    nativeSetParameterVec3
 * Signature: (Ljava/lang/String;FFF)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_Shader_nativeSetParameterVec3
  (JNIEnv *, jobject, jstring, jfloat, jfloat, jfloat);

/*
 * Class:     org_jsfml_graphics_Shader
 * Method:    nativeSetParameterVec4
 * Signature: (Ljava/lang/String;FFFF)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_Shader_nativeSetParameterVec4
  (JNIEnv *, jobject, jstring, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_jsfml_graphics_Shader
 * Method:    nativeSetParameterMat4
 * Signature: (Ljava/lang/String;Ljava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_Shader_nativeSetParameterMat4
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     org_jsfml_graphics_Shader
 * Method:    nativeSetParameterSampler2d
 * Signature: (Ljava/lang/String;Lorg/jsfml/graphics/Texture;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_Shader_nativeSetParameterSampler2d
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     org_jsfml_graphics_Shader
 * Method:    nativeSetParameterCurrentTexture
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_Shader_nativeSetParameterCurrentTexture
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
