/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_graphics_View */

#ifndef _Included_org_jsfml_graphics_View
#define _Included_org_jsfml_graphics_View
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jsfml_graphics_View
 * Method:    nativeCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jsfml_graphics_View_nativeCreate
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_graphics_View
 * Method:    nativeDelete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_View_nativeDelete
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_graphics_View
 * Method:    nativeSetCenter
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_View_nativeSetCenter
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     org_jsfml_graphics_View
 * Method:    nativeSetSize
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_View_nativeSetSize
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     org_jsfml_graphics_View
 * Method:    nativeSetRotation
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_View_nativeSetRotation
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     org_jsfml_graphics_View
 * Method:    nativeSetViewport
 * Signature: (Ljava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_View_nativeSetViewport
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_jsfml_graphics_View
 * Method:    nativeReset
 * Signature: (Ljava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_View_nativeReset
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_jsfml_graphics_View
 * Method:    nativeGetViewport
 * Signature: (Ljava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_View_nativeGetViewport
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_jsfml_graphics_View
 * Method:    nativeGetSize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jsfml_graphics_View_nativeGetSize
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_graphics_View
 * Method:    nativeGetCenter
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jsfml_graphics_View_nativeGetCenter
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_graphics_View
 * Method:    nativeGetRotation
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_jsfml_graphics_View_nativeGetRotation
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_graphics_View
 * Method:    nativeGetTransform
 * Signature: (Ljava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_View_nativeGetTransform
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
