/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_audio_Listener */

#ifndef _Included_org_jsfml_audio_Listener
#define _Included_org_jsfml_audio_Listener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jsfml_audio_Listener
 * Method:    setGlobalVolume
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_audio_Listener_setGlobalVolume
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     org_jsfml_audio_Listener
 * Method:    getGlobalVolume
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_jsfml_audio_Listener_getGlobalVolume
  (JNIEnv *, jclass);

/*
 * Class:     org_jsfml_audio_Listener
 * Method:    setPosition
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_audio_Listener_setPosition
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     org_jsfml_audio_Listener
 * Method:    getPosition
 * Signature: ()Lorg/jsfml/system/Vector3f;
 */
JNIEXPORT jobject JNICALL Java_org_jsfml_audio_Listener_getPosition
  (JNIEnv *, jclass);

/*
 * Class:     org_jsfml_audio_Listener
 * Method:    setDirection
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_audio_Listener_setDirection
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     org_jsfml_audio_Listener
 * Method:    getDirection
 * Signature: ()Lorg/jsfml/system/Vector3f;
 */
JNIEXPORT jobject JNICALL Java_org_jsfml_audio_Listener_getDirection
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
