/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_graphics_Font */

#ifndef _Included_org_jsfml_graphics_Font
#define _Included_org_jsfml_graphics_Font
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: debug */
/* Inaccessible static: numManaged */
/* Inaccessible static: numWrapped */
/*
 * Class:     org_jsfml_graphics_Font
 * Method:    nativeCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jsfml_graphics_Font_nativeCreate
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_graphics_Font
 * Method:    nativeDelete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_Font_nativeDelete
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_graphics_Font
 * Method:    nativeCopy
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jsfml_graphics_Font_nativeCopy
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_graphics_Font
 * Method:    nativeLoadFromMemory
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_org_jsfml_graphics_Font_nativeLoadFromMemory
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_jsfml_graphics_Font
 * Method:    nativeReleaseMemory
 * Signature: ([BJ)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_Font_nativeReleaseMemory
  (JNIEnv *, jobject, jbyteArray, jlong);

/*
 * Class:     org_jsfml_graphics_Font
 * Method:    getGlyph
 * Signature: (IIZ)Lorg/jsfml/graphics/Glyph;
 */
JNIEXPORT jobject JNICALL Java_org_jsfml_graphics_Font_getGlyph
  (JNIEnv *, jobject, jint, jint, jboolean);

/*
 * Class:     org_jsfml_graphics_Font
 * Method:    getKerning
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_org_jsfml_graphics_Font_getKerning
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_jsfml_graphics_Font
 * Method:    getLineSpacing
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_jsfml_graphics_Font_getLineSpacing
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_jsfml_graphics_Font
 * Method:    nativeGetTexture
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_jsfml_graphics_Font_nativeGetTexture
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
