/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_window_Window */

#ifndef _Included_org_jsfml_window_Window
#define _Included_org_jsfml_window_Window
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: debug */
/* Inaccessible static: numManaged */
/* Inaccessible static: numWrapped */
#undef org_jsfml_window_Window_NONE
#define org_jsfml_window_Window_NONE 0L
#undef org_jsfml_window_Window_TITLEBAR
#define org_jsfml_window_Window_TITLEBAR 1L
#undef org_jsfml_window_Window_RESIZE
#define org_jsfml_window_Window_RESIZE 2L
#undef org_jsfml_window_Window_CLOSE
#define org_jsfml_window_Window_CLOSE 4L
#undef org_jsfml_window_Window_FULLSCREEN
#define org_jsfml_window_Window_FULLSCREEN 8L
#undef org_jsfml_window_Window_DEFAULT
#define org_jsfml_window_Window_DEFAULT 7L
/*
 * Class:     org_jsfml_window_Window
 * Method:    nativeCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jsfml_window_Window_nativeCreate__
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_window_Window
 * Method:    nativeDelete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jsfml_window_Window_nativeDelete
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_window_Window
 * Method:    nativeCreate
 * Signature: (Lorg/jsfml/window/VideoMode;Ljava/lang/String;ILorg/jsfml/window/ContextSettings;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_window_Window_nativeCreate__Lorg_jsfml_window_VideoMode_2Ljava_lang_String_2ILorg_jsfml_window_ContextSettings_2
  (JNIEnv *, jobject, jobject, jstring, jint, jobject);

/*
 * Class:     org_jsfml_window_Window
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jsfml_window_Window_close
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_window_Window
 * Method:    isOpen
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_jsfml_window_Window_isOpen
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_window_Window
 * Method:    getPosition
 * Signature: ()Lorg/jsfml/system/Vector2i;
 */
JNIEXPORT jobject JNICALL Java_org_jsfml_window_Window_getPosition
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_window_Window
 * Method:    nativeSetPosition
 * Signature: (Lorg/jsfml/system/Vector2i;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_window_Window_nativeSetPosition
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_jsfml_window_Window
 * Method:    getSize
 * Signature: ()Lorg/jsfml/system/Vector2i;
 */
JNIEXPORT jobject JNICALL Java_org_jsfml_window_Window_getSize
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_window_Window
 * Method:    nativeSetSize
 * Signature: (Lorg/jsfml/system/Vector2i;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_window_Window_nativeSetSize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_jsfml_window_Window
 * Method:    getSettings
 * Signature: ()Lorg/jsfml/window/ContextSettings;
 */
JNIEXPORT jobject JNICALL Java_org_jsfml_window_Window_getSettings
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_window_Window
 * Method:    pollEvent
 * Signature: ()Lorg/jsfml/window/event/Event;
 */
JNIEXPORT jobject JNICALL Java_org_jsfml_window_Window_pollEvent
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_window_Window
 * Method:    waitEvent
 * Signature: ()Lorg/jsfml/window/event/Event;
 */
JNIEXPORT jobject JNICALL Java_org_jsfml_window_Window_waitEvent
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_window_Window
 * Method:    setVerticalSyncEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_window_Window_setVerticalSyncEnabled
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_jsfml_window_Window
 * Method:    setMouseCursorVisible
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_window_Window_setMouseCursorVisible
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_jsfml_window_Window
 * Method:    nativeSetTitle
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_window_Window_nativeSetTitle
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_jsfml_window_Window
 * Method:    setVisible
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_window_Window_setVisible
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_jsfml_window_Window
 * Method:    setKeyRepeatEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_window_Window_setKeyRepeatEnabled
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_jsfml_window_Window
 * Method:    nativeSetIcon
 * Signature: (Lorg/jsfml/graphics/Image;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_window_Window_nativeSetIcon
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_jsfml_window_Window
 * Method:    setActive
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_window_Window_setActive
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_jsfml_window_Window
 * Method:    display
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jsfml_window_Window_display
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_window_Window
 * Method:    setFramerateLimit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_window_Window_setFramerateLimit
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_jsfml_window_Window
 * Method:    setJoystickTreshold
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_window_Window_setJoystickTreshold
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
