/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_graphics_RenderTarget */

#ifndef _Included_org_jsfml_graphics_RenderTarget
#define _Included_org_jsfml_graphics_RenderTarget
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jsfml_graphics_RenderTarget_EXPTR_RENDER_TARGET
#define org_jsfml_graphics_RenderTarget_EXPTR_RENDER_TARGET 0L
#ifdef __cplusplus
}
#endif
#endif
