/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_SFMLNativeObject */

#ifndef _Included_org_jsfml_SFMLNativeObject
#define _Included_org_jsfml_SFMLNativeObject
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: debug */
/* Inaccessible static: numManaged */
/* Inaccessible static: numWrapped */
/*
 * Class:     org_jsfml_SFMLNativeObject
 * Method:    nativeDelete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jsfml_SFMLNativeObject_nativeDelete
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
