/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_window_Joystick */

#ifndef _Included_org_jsfml_window_Joystick
#define _Included_org_jsfml_window_Joystick
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jsfml_window_Joystick_JOYSTICK_COUNT
#define org_jsfml_window_Joystick_JOYSTICK_COUNT 8L
#undef org_jsfml_window_Joystick_BUTTON_COUNT
#define org_jsfml_window_Joystick_BUTTON_COUNT 32L
/*
 * Class:     org_jsfml_window_Joystick
 * Method:    nativeIsConnected
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jsfml_window_Joystick_nativeIsConnected
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jsfml_window_Joystick
 * Method:    nativeGetButtonCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_jsfml_window_Joystick_nativeGetButtonCount
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jsfml_window_Joystick
 * Method:    nativeHasAxis
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jsfml_window_Joystick_nativeHasAxis
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_jsfml_window_Joystick
 * Method:    nativeIsButtonPressed
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jsfml_window_Joystick_nativeIsButtonPressed
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_jsfml_window_Joystick
 * Method:    nativeGetAxisPosition
 * Signature: (II)F
 */
JNIEXPORT jfloat JNICALL Java_org_jsfml_window_Joystick_nativeGetAxisPosition
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_jsfml_window_Joystick
 * Method:    update
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jsfml_window_Joystick_update
  (JNIEnv *, jclass);

/*
 * Class:     org_jsfml_window_Joystick
 * Method:    nativeGetIdentification
 * Signature: (ILjava/nio/Buffer;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jsfml_window_Joystick_nativeGetIdentification
  (JNIEnv *, jclass, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
