/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_window_Mouse */

#ifndef _Included_org_jsfml_window_Mouse
#define _Included_org_jsfml_window_Mouse
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jsfml_window_Mouse
 * Method:    nativeIsButtonPressed
 * Signature: (Lorg/jsfml/window/Mouse/Button;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jsfml_window_Mouse_nativeIsButtonPressed
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_jsfml_window_Mouse
 * Method:    getPosition
 * Signature: ()Lorg/jsfml/system/Vector2i;
 */
JNIEXPORT jobject JNICALL Java_org_jsfml_window_Mouse_getPosition
  (JNIEnv *, jclass);

/*
 * Class:     org_jsfml_window_Mouse
 * Method:    nativeGetPosition
 * Signature: (Lorg/jsfml/window/Window;)Lorg/jsfml/system/Vector2i;
 */
JNIEXPORT jobject JNICALL Java_org_jsfml_window_Mouse_nativeGetPosition
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_jsfml_window_Mouse
 * Method:    nativeSetPosition
 * Signature: (Lorg/jsfml/system/Vector2i;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_window_Mouse_nativeSetPosition__Lorg_jsfml_system_Vector2i_2
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_jsfml_window_Mouse
 * Method:    nativeSetPosition
 * Signature: (Lorg/jsfml/system/Vector2i;Lorg/jsfml/window/Window;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_window_Mouse_nativeSetPosition__Lorg_jsfml_system_Vector2i_2Lorg_jsfml_window_Window_2
  (JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
