/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_audio_Listener */

#ifndef _Included_org_jsfml_audio_Listener
#define _Included_org_jsfml_audio_Listener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jsfml_audio_Listener
 * Method:    nativeSetGlobalVolume
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_audio_Listener_nativeSetGlobalVolume
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     org_jsfml_audio_Listener
 * Method:    nativeSetPosition
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_audio_Listener_nativeSetPosition
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     org_jsfml_audio_Listener
 * Method:    nativeSetDirection
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_audio_Listener_nativeSetDirection
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     org_jsfml_audio_Listener
 * Method:    nativeSetUpVector
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_audio_Listener_nativeSetUpVector
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
