/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_graphics_VertexArray */

#ifndef _Included_org_jsfml_graphics_VertexArray
#define _Included_org_jsfml_graphics_VertexArray
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: debug */
/* Inaccessible static: numManaged */
/* Inaccessible static: numWrapped */
/*
 * Class:     org_jsfml_graphics_VertexArray
 * Method:    nativeCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jsfml_graphics_VertexArray_nativeCreate
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_graphics_VertexArray
 * Method:    nativeDelete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_VertexArray_nativeDelete
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_graphics_VertexArray
 * Method:    getVertexCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jsfml_graphics_VertexArray_getVertexCount
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_graphics_VertexArray
 * Method:    nativeGetVertex
 * Signature: (I)Lorg/jsfml/graphics/Vertex;
 */
JNIEXPORT jobject JNICALL Java_org_jsfml_graphics_VertexArray_nativeGetVertex
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_jsfml_graphics_VertexArray
 * Method:    nativeSetVertex
 * Signature: (ILorg/jsfml/graphics/Vertex;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_VertexArray_nativeSetVertex
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_jsfml_graphics_VertexArray
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_VertexArray_clear
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_graphics_VertexArray
 * Method:    nativeResize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_VertexArray_nativeResize
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_jsfml_graphics_VertexArray
 * Method:    nativeAppend
 * Signature: (Lorg/jsfml/graphics/Vertex;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_VertexArray_nativeAppend
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_jsfml_graphics_VertexArray
 * Method:    nativeSetPrimitiveType
 * Signature: (Lorg/jsfml/graphics/PrimitiveType;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_VertexArray_nativeSetPrimitiveType
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_jsfml_graphics_VertexArray
 * Method:    nativeGetPrimitiveType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jsfml_graphics_VertexArray_nativeGetPrimitiveType
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_graphics_VertexArray
 * Method:    getBounds
 * Signature: ()Lorg/jsfml/graphics/FloatRect;
 */
JNIEXPORT jobject JNICALL Java_org_jsfml_graphics_VertexArray_getBounds
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
