/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_window_Window */

#ifndef _Included_org_jsfml_window_Window
#define _Included_org_jsfml_window_Window
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jsfml_window_Window
 * Method:    nativeCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jsfml_window_Window_nativeCreate
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_window_Window
 * Method:    nativeSetExPtr
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jsfml_window_Window_nativeSetExPtr
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_window_Window
 * Method:    nativeDelete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jsfml_window_Window_nativeDelete
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_window_Window
 * Method:    nativeCreateWindow
 * Signature: (Ljava/nio/Buffer;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_window_Window_nativeCreateWindow
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     org_jsfml_window_Window
 * Method:    isLegalWindowThread
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_jsfml_window_Window_isLegalWindowThread
  (JNIEnv *, jclass);

/*
 * Class:     org_jsfml_window_Window
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jsfml_window_Window_close
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_window_Window
 * Method:    isOpen
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_jsfml_window_Window_isOpen
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_window_Window
 * Method:    nativeGetPosition
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jsfml_window_Window_nativeGetPosition
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_window_Window
 * Method:    nativeSetPosition
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_window_Window_nativeSetPosition
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_jsfml_window_Window
 * Method:    nativeGetSize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jsfml_window_Window_nativeGetSize
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_window_Window
 * Method:    nativeSetSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_window_Window_nativeSetSize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_jsfml_window_Window
 * Method:    nativeGetSettings
 * Signature: (Ljava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_window_Window_nativeGetSettings
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_jsfml_window_Window
 * Method:    nativePollEvent
 * Signature: (Ljava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_window_Window_nativePollEvent
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_jsfml_window_Window
 * Method:    nativeWaitEvent
 * Signature: (Ljava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_window_Window_nativeWaitEvent
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_jsfml_window_Window
 * Method:    setVerticalSyncEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_window_Window_setVerticalSyncEnabled
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_jsfml_window_Window
 * Method:    setMouseCursorVisible
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_window_Window_setMouseCursorVisible
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_jsfml_window_Window
 * Method:    nativeSetTitle
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_window_Window_nativeSetTitle
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_jsfml_window_Window
 * Method:    setVisible
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_window_Window_setVisible
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_jsfml_window_Window
 * Method:    setKeyRepeatEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_window_Window_setKeyRepeatEnabled
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_jsfml_window_Window
 * Method:    nativeSetIcon
 * Signature: (Lorg/jsfml/graphics/Image;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_window_Window_nativeSetIcon
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_jsfml_window_Window
 * Method:    nativeSetActive
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jsfml_window_Window_nativeSetActive
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_jsfml_window_Window
 * Method:    display
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jsfml_window_Window_display
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_window_Window
 * Method:    setFramerateLimit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_window_Window_setFramerateLimit
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_jsfml_window_Window
 * Method:    setJoystickTreshold
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_window_Window_setJoystickTreshold
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
