/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_audio_SoundRecorder */

#ifndef _Included_org_jsfml_audio_SoundRecorder
#define _Included_org_jsfml_audio_SoundRecorder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jsfml_audio_SoundRecorder
 * Method:    isAvailable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_jsfml_audio_SoundRecorder_isAvailable
  (JNIEnv *, jclass);

/*
 * Class:     org_jsfml_audio_SoundRecorder
 * Method:    getAvailableDevices
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_jsfml_audio_SoundRecorder_getAvailableDevices
  (JNIEnv *, jclass);

/*
 * Class:     org_jsfml_audio_SoundRecorder
 * Method:    getDefaultDevice
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jsfml_audio_SoundRecorder_getDefaultDevice
  (JNIEnv *, jclass);

/*
 * Class:     org_jsfml_audio_SoundRecorder
 * Method:    nativeCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jsfml_audio_SoundRecorder_nativeCreate
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_audio_SoundRecorder
 * Method:    nativeSetExPtr
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jsfml_audio_SoundRecorder_nativeSetExPtr
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_audio_SoundRecorder
 * Method:    nativeDelete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jsfml_audio_SoundRecorder_nativeDelete
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_audio_SoundRecorder
 * Method:    nativeStart
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jsfml_audio_SoundRecorder_nativeStart
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_jsfml_audio_SoundRecorder
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jsfml_audio_SoundRecorder_stop
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_audio_SoundRecorder
 * Method:    nativeSetProcessingInterval
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_audio_SoundRecorder_nativeSetProcessingInterval
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_jsfml_audio_SoundRecorder
 * Method:    nativeSetDevice
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jsfml_audio_SoundRecorder_nativeSetDevice
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
