/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_audio_Music */

#ifndef _Included_org_jsfml_audio_Music
#define _Included_org_jsfml_audio_Music
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jsfml_audio_Music
 * Method:    nativeCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jsfml_audio_Music_nativeCreate
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_audio_Music
 * Method:    nativeSetExPtr
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jsfml_audio_Music_nativeSetExPtr
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_audio_Music
 * Method:    nativeDelete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jsfml_audio_Music_nativeDelete
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_audio_Music
 * Method:    nativeOpenFromStream
 * Signature: (Lorg/jsfml/internal/SFMLInputStream/NativeStreamRef;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jsfml_audio_Music_nativeOpenFromStream
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_jsfml_audio_Music
 * Method:    nativeGetData
 * Signature: (Ljava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_audio_Music_nativeGetData
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
