/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_internal_SFMLInputStream_NativeStreamRef */

#ifndef _Included_org_jsfml_internal_SFMLInputStream_NativeStreamRef
#define _Included_org_jsfml_internal_SFMLInputStream_NativeStreamRef
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jsfml_internal_SFMLInputStream_NativeStreamRef
 * Method:    nativeInitialize
 * Signature: (Lorg/jsfml/internal/SFMLInputStream;)J
 */
JNIEXPORT jlong JNICALL Java_org_jsfml_internal_SFMLInputStream_00024NativeStreamRef_nativeInitialize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_jsfml_internal_SFMLInputStream_NativeStreamRef
 * Method:    nativeRelease
 * Signature: (Lorg/jsfml/internal/SFMLInputStream;J)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_internal_SFMLInputStream_00024NativeStreamRef_nativeRelease
  (JNIEnv *, jobject, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
