/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_graphics_SFMLNativeDrawer */

#ifndef _Included_org_jsfml_graphics_SFMLNativeDrawer
#define _Included_org_jsfml_graphics_SFMLNativeDrawer
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jsfml_graphics_SFMLNativeDrawer_NATIVE_VERTEX_SIZE
#define org_jsfml_graphics_SFMLNativeDrawer_NATIVE_VERTEX_SIZE 20L
/*
 * Class:     org_jsfml_graphics_SFMLNativeDrawer
 * Method:    nativeDrawVertices
 * Signature: (ILjava/nio/Buffer;ILorg/jsfml/graphics/RenderTarget;Ljava/nio/Buffer;Lorg/jsfml/graphics/ConstTexture;Lorg/jsfml/graphics/ConstShader;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_SFMLNativeDrawer_nativeDrawVertices
  (JNIEnv *, jclass, jint, jobject, jint, jobject, jobject, jobject, jobject);

/*
 * Class:     org_jsfml_graphics_SFMLNativeDrawer
 * Method:    nativeDrawDrawable
 * Signature: (Lorg/jsfml/graphics/Drawable;Lorg/jsfml/graphics/RenderTarget;Ljava/nio/Buffer;Lorg/jsfml/graphics/ConstTexture;Lorg/jsfml/graphics/ConstShader;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_SFMLNativeDrawer_nativeDrawDrawable
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
