/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_audio_SoundSource */

#ifndef _Included_org_jsfml_audio_SoundSource
#define _Included_org_jsfml_audio_SoundSource
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jsfml_audio_SoundSource
 * Method:    nativeGetData
 * Signature: (Ljava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_audio_SoundSource_nativeGetData
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_jsfml_audio_SoundSource
 * Method:    nativeSetPitch
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_audio_SoundSource_nativeSetPitch
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     org_jsfml_audio_SoundSource
 * Method:    nativeSetVolume
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_audio_SoundSource_nativeSetVolume
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     org_jsfml_audio_SoundSource
 * Method:    nativeSetPosition
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_audio_SoundSource_nativeSetPosition
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     org_jsfml_audio_SoundSource
 * Method:    nativeSetRelativeToListener
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_audio_SoundSource_nativeSetRelativeToListener
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_jsfml_audio_SoundSource
 * Method:    nativeSetMinDistance
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_audio_SoundSource_nativeSetMinDistance
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     org_jsfml_audio_SoundSource
 * Method:    nativeSetAttenuation
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_audio_SoundSource_nativeSetAttenuation
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
