/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_graphics_DrawableNativeImpl */

#ifndef _Included_org_jsfml_graphics_DrawableNativeImpl
#define _Included_org_jsfml_graphics_DrawableNativeImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jsfml_graphics_DrawableNativeImpl
 * Method:    nativeDraw
 * Signature: (Lorg/jsfml/graphics/Drawable;Lorg/jsfml/graphics/RenderTarget;Lorg/jsfml/graphics/RenderStates;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_DrawableNativeImpl_nativeDraw
  (JNIEnv *, jclass, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
