/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_window_Mouse_Button */

#ifndef _Included_org_jsfml_window_Mouse_Button
#define _Included_org_jsfml_window_Mouse_Button
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
