/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_internal_ExPtr */

#ifndef _Included_org_jsfml_internal_ExPtr
#define _Included_org_jsfml_internal_ExPtr
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jsfml_internal_ExPtr_NUM
#define org_jsfml_internal_ExPtr_NUM 3L
#undef org_jsfml_internal_ExPtr_DRAWABLE
#define org_jsfml_internal_ExPtr_DRAWABLE 0L
#undef org_jsfml_internal_ExPtr_TRANSFORMABLE
#define org_jsfml_internal_ExPtr_TRANSFORMABLE 1L
#undef org_jsfml_internal_ExPtr_SHAPE
#define org_jsfml_internal_ExPtr_SHAPE 2L
#undef org_jsfml_internal_ExPtr_RENDER_TARGET
#define org_jsfml_internal_ExPtr_RENDER_TARGET 0L
#undef org_jsfml_internal_ExPtr_WINDOW
#define org_jsfml_internal_ExPtr_WINDOW 1L
#undef org_jsfml_internal_ExPtr_SOUND_SOURCE
#define org_jsfml_internal_ExPtr_SOUND_SOURCE 0L
#undef org_jsfml_internal_ExPtr_SOUND_STREAM
#define org_jsfml_internal_ExPtr_SOUND_STREAM 1L
#ifdef __cplusplus
}
#endif
#endif
