/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_JSFML */

#ifndef _Included_org_jsfml_JSFML
#define _Included_org_jsfml_JSFML
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jsfml_JSFML_JSFML_RELEASE_NUMBER
#define org_jsfml_JSFML_JSFML_RELEASE_NUMBER 6L
/*
 * Class:     org_jsfml_JSFML
 * Method:    nativeGetSFMLVersion
 * Signature: (Ljava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_JSFML_nativeGetSFMLVersion
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
