/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_graphics_Text */

#ifndef _Included_org_jsfml_graphics_Text
#define _Included_org_jsfml_graphics_Text
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jsfml_graphics_Text
 * Method:    nativeCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jsfml_graphics_Text_nativeCreate
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_graphics_Text
 * Method:    nativeSetExPtr
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_Text_nativeSetExPtr
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_graphics_Text
 * Method:    nativeDelete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_Text_nativeDelete
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_graphics_Text
 * Method:    nativeSetString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_Text_nativeSetString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_jsfml_graphics_Text
 * Method:    nativeSetFont
 * Signature: (Lorg/jsfml/graphics/Font;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_Text_nativeSetFont
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_jsfml_graphics_Text
 * Method:    setCharacterSize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_Text_setCharacterSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_jsfml_graphics_Text
 * Method:    setStyle
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_Text_setStyle
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_jsfml_graphics_Text
 * Method:    nativeSetColor
 * Signature: (Lorg/jsfml/graphics/Color;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_Text_nativeSetColor
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_jsfml_graphics_Text
 * Method:    getCharacterSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jsfml_graphics_Text_getCharacterSize
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_graphics_Text
 * Method:    getStyle
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jsfml_graphics_Text_getStyle
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_graphics_Text
 * Method:    getColor
 * Signature: ()Lorg/jsfml/graphics/Color;
 */
JNIEXPORT jobject JNICALL Java_org_jsfml_graphics_Text_getColor
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_graphics_Text
 * Method:    nativeFindCharacterPos
 * Signature: (I)Lorg/jsfml/system/Vector2f;
 */
JNIEXPORT jobject JNICALL Java_org_jsfml_graphics_Text_nativeFindCharacterPos
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_jsfml_graphics_Text
 * Method:    getLocalBounds
 * Signature: ()Lorg/jsfml/graphics/FloatRect;
 */
JNIEXPORT jobject JNICALL Java_org_jsfml_graphics_Text_getLocalBounds
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_graphics_Text
 * Method:    getGlobalBounds
 * Signature: ()Lorg/jsfml/graphics/FloatRect;
 */
JNIEXPORT jobject JNICALL Java_org_jsfml_graphics_Text_getGlobalBounds
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
