/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_system_Clock */

#ifndef _Included_org_jsfml_system_Clock
#define _Included_org_jsfml_system_Clock
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: debug */
/* Inaccessible static: numManaged */
/* Inaccessible static: numWrapped */
/*
 * Class:     org_jsfml_system_Clock
 * Method:    nativeCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jsfml_system_Clock_nativeCreate
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_system_Clock
 * Method:    nativeDelete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jsfml_system_Clock_nativeDelete
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_system_Clock
 * Method:    getElapsedTime
 * Signature: ()Lorg/jsfml/system/Time;
 */
JNIEXPORT jobject JNICALL Java_org_jsfml_system_Clock_getElapsedTime
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_system_Clock
 * Method:    restart
 * Signature: ()Lorg/jsfml/system/Time;
 */
JNIEXPORT jobject JNICALL Java_org_jsfml_system_Clock_restart
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
