/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_audio_SoundRecorder */

#ifndef _Included_org_jsfml_audio_SoundRecorder
#define _Included_org_jsfml_audio_SoundRecorder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jsfml_audio_SoundRecorder
 * Method:    isAvailable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_jsfml_audio_SoundRecorder_isAvailable
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
