/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_audio_SoundStream_Chunk */

#ifndef _Included_org_jsfml_audio_SoundStream_Chunk
#define _Included_org_jsfml_audio_SoundStream_Chunk
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
