/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_window_VideoMode */

#ifndef _Included_org_jsfml_window_VideoMode
#define _Included_org_jsfml_window_VideoMode
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jsfml_window_VideoMode_serialVersionUID
#define org_jsfml_window_VideoMode_serialVersionUID 8608938390916786270i64
/*
 * Class:     org_jsfml_window_VideoMode
 * Method:    getDesktopMode
 * Signature: ()Lorg/jsfml/window/VideoMode;
 */
JNIEXPORT jobject JNICALL Java_org_jsfml_window_VideoMode_getDesktopMode
  (JNIEnv *, jclass);

/*
 * Class:     org_jsfml_window_VideoMode
 * Method:    getFullscreenModes
 * Signature: ()[Lorg/jsfml/window/VideoMode;
 */
JNIEXPORT jobjectArray JNICALL Java_org_jsfml_window_VideoMode_getFullscreenModes
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
