/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_graphics_Texture */

#ifndef _Included_org_jsfml_graphics_Texture
#define _Included_org_jsfml_graphics_Texture
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jsfml_graphics_Texture
 * Method:    nativeGetMaximumSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jsfml_graphics_Texture_nativeGetMaximumSize
  (JNIEnv *, jclass);

/*
 * Class:     org_jsfml_graphics_Texture
 * Method:    nativeBind
 * Signature: (Lorg/jsfml/graphics/Texture;Lorg/jsfml/graphics/Texture/CoordinateType;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_Texture_nativeBind
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     org_jsfml_graphics_Texture
 * Method:    nativeCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jsfml_graphics_Texture_nativeCreate__
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_graphics_Texture
 * Method:    nativeDelete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_Texture_nativeDelete
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_graphics_Texture
 * Method:    nativeCopy
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jsfml_graphics_Texture_nativeCopy
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_graphics_Texture
 * Method:    nativeCreate
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jsfml_graphics_Texture_nativeCreate__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_jsfml_graphics_Texture
 * Method:    nativeLoadFromMemory
 * Signature: ([BLjava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jsfml_graphics_Texture_nativeLoadFromMemory
  (JNIEnv *, jobject, jbyteArray, jobject);

/*
 * Class:     org_jsfml_graphics_Texture
 * Method:    nativeLoadFromImage
 * Signature: (Lorg/jsfml/graphics/Image;Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jsfml_graphics_Texture_nativeLoadFromImage
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_jsfml_graphics_Texture
 * Method:    nativeGetSize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jsfml_graphics_Texture_nativeGetSize
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_graphics_Texture
 * Method:    nativeCopyToImage
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jsfml_graphics_Texture_nativeCopyToImage
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_graphics_Texture
 * Method:    nativeUpdate
 * Signature: (Lorg/jsfml/graphics/Image;II)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_Texture_nativeUpdate__Lorg_jsfml_graphics_Image_2II
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     org_jsfml_graphics_Texture
 * Method:    nativeUpdate
 * Signature: (Lorg/jsfml/window/Window;II)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_Texture_nativeUpdate__Lorg_jsfml_window_Window_2II
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     org_jsfml_graphics_Texture
 * Method:    nativeSetSmooth
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_Texture_nativeSetSmooth
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_jsfml_graphics_Texture
 * Method:    nativeSetRepeated
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_graphics_Texture_nativeSetRepeated
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
