/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_window_Joystick_Identification */

#ifndef _Included_org_jsfml_window_Joystick_Identification
#define _Included_org_jsfml_window_Joystick_Identification
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jsfml_window_Joystick_Identification_serialVersionUID
#define org_jsfml_window_Joystick_Identification_serialVersionUID 4831994862885876452i64
#ifdef __cplusplus
}
#endif
#endif
