/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_graphics_Texture_CoordinateType */

#ifndef _Included_org_jsfml_graphics_Texture_CoordinateType
#define _Included_org_jsfml_graphics_Texture_CoordinateType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
