/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_window_Context */

#ifndef _Included_org_jsfml_window_Context
#define _Included_org_jsfml_window_Context
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: debug */
/* Inaccessible static: numManaged */
/* Inaccessible static: numWrapped */
/*
 * Class:     org_jsfml_window_Context
 * Method:    nativeCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jsfml_window_Context_nativeCreate
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_window_Context
 * Method:    nativeDelete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jsfml_window_Context_nativeDelete
  (JNIEnv *, jobject);

/*
 * Class:     org_jsfml_window_Context
 * Method:    nativeSetActive
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jsfml_window_Context_nativeSetActive
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
