/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_window_Mouse */

#ifndef _Included_org_jsfml_window_Mouse
#define _Included_org_jsfml_window_Mouse
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jsfml_window_Mouse
 * Method:    nativeIsButtonPressed
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jsfml_window_Mouse_nativeIsButtonPressed
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jsfml_window_Mouse
 * Method:    nativeGetPosition
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jsfml_window_Mouse_nativeGetPosition__
  (JNIEnv *, jclass);

/*
 * Class:     org_jsfml_window_Mouse
 * Method:    nativeGetPosition
 * Signature: (Lorg/jsfml/window/Window;)J
 */
JNIEXPORT jlong JNICALL Java_org_jsfml_window_Mouse_nativeGetPosition__Lorg_jsfml_window_Window_2
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_jsfml_window_Mouse
 * Method:    nativeSetPosition
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_window_Mouse_nativeSetPosition__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jsfml_window_Mouse
 * Method:    nativeSetPosition
 * Signature: (JLorg/jsfml/window/Window;)V
 */
JNIEXPORT void JNICALL Java_org_jsfml_window_Mouse_nativeSetPosition__JLorg_jsfml_window_Window_2
  (JNIEnv *, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
