/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_internal_SFMLErrorCapture */

#ifndef _Included_org_jsfml_internal_SFMLErrorCapture
#define _Included_org_jsfml_internal_SFMLErrorCapture
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jsfml_internal_SFMLErrorCapture
 * Method:    nativeStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jsfml_internal_SFMLErrorCapture_nativeStart
  (JNIEnv *, jclass);

/*
 * Class:     org_jsfml_internal_SFMLErrorCapture
 * Method:    nativeFinish
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jsfml_internal_SFMLErrorCapture_nativeFinish
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
